'use client';

import { PencilLine, Plus, Save, X } from 'lucide-react';
import { type FormEvent, useState } from 'react';
import { useI18n } from '@/lib/i18n/useI18n';
import {
  DEFAULT_OUTPUT_DESTINATION,
  DEFAULT_OUTPUT_DESTINATION_LABEL,
  DEFAULT_OUTPUT_TYPE,
  NEW_SPACE_DESTINATION,
  OUTPUT_TYPES,
  WEEKDAY_OPTIONS,
  getDefaultScheduleType,
  normalizeScheduleType,
  normalizeStoredAutomationForRuntime,
} from './helpers';
import type {
  AutomationMode,
  AutomationScheduleType,
  AutomationSpace,
  AutomationStatus,
  StoredAutomation,
} from './types';

export const AutomationBuilder = ({
  editingAutomation,
  spaces,
  onCancel,
  onSave,
  onCreateSpace,
}: {
  editingAutomation?: StoredAutomation | null;
  spaces: AutomationSpace[];
  onCancel: () => void;
  onSave: (automation: StoredAutomation) => void;
  onCreateSpace: (name: string) => Promise<AutomationSpace | null>;
}) => {
  const { t } = useI18n();
  const isEditing = Boolean(editingAutomation);

  const [name, setName] = useState(editingAutomation?.name ?? '');
  const [category, setCategory] = useState(
    editingAutomation?.category ?? 'Research',
  );
  const [frequency, setFrequency] = useState(
    editingAutomation?.frequency ?? 'Every Tuesday',
  );
  const [mode, setMode] = useState<AutomationMode>(editingAutomation?.mode ?? 'manual');
  const [status, setStatus] = useState<AutomationStatus>(editingAutomation?.status ?? 'active');
  const [scheduleType, setScheduleType] = useState<AutomationScheduleType>(
    editingAutomation?.scheduleType ?? getDefaultScheduleType(editingAutomation?.frequency ?? 'Manual'),
  );
  const [scheduleTime, setScheduleTime] = useState(editingAutomation?.scheduleTime ?? '09:00');
  const [scheduleDays, setScheduleDays] = useState<string[]>(editingAutomation?.scheduleDays ?? ['MO']);
  const [scheduleDayOfMonth, setScheduleDayOfMonth] = useState(
    editingAutomation?.scheduleDayOfMonth ?? 1,
  );
  const [purpose, setPurpose] = useState(editingAutomation?.purpose ?? '');
  const [prompt, setPrompt] = useState(editingAutomation?.prompt ?? '');
  const [output, setOutput] = useState(editingAutomation?.output ?? '');
  const [outputType, setOutputType] = useState(
    editingAutomation?.outputType ?? 'Article',
  );
  const [outputDestination, setOutputDestination] = useState(
    editingAutomation?.outputDestination ?? DEFAULT_OUTPUT_DESTINATION,
  );
  const [newSpaceName, setNewSpaceName] = useState('');

  const canSave =
    name.trim().length > 0 &&
    prompt.trim().length > 0 &&
    (outputDestination !== NEW_SPACE_DESTINATION ||
      newSpaceName.trim().length > 0);

  const setTestScheduleInTwoMinutes = () => {
    const date = new Date(Date.now() + 2 * 60 * 1000);
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');

    setMode('auto');
    setStatus('active');
    setScheduleType('daily');
    setScheduleTime(`${hours}:${minutes}`);
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!canSave) return;

    let finalOutputDestination = outputDestination;
    let outputDestinationLabel =
      outputDestination === DEFAULT_OUTPUT_DESTINATION
        ? DEFAULT_OUTPUT_DESTINATION_LABEL
        : spaces.find((space) => `space:${space.id}` === outputDestination)
            ?.name ?? DEFAULT_OUTPUT_DESTINATION_LABEL;

    if (outputDestination === NEW_SPACE_DESTINATION) {
      const createdSpace = await onCreateSpace(newSpaceName.trim());

      if (!createdSpace) return;

      finalOutputDestination = `space:${createdSpace.id}`;
      outputDestinationLabel = createdSpace.name;
    }

    onSave(normalizeStoredAutomationForRuntime({
      id: editingAutomation?.id ?? `custom-${Date.now()}`,
      name: name.trim(),
      category: category.trim() || 'Custom',
      frequency: frequency.trim() || 'Manual',
      mode,
      status,
      scheduleType: normalizeScheduleType(scheduleType, frequency),
      scheduleTime,
      scheduleDays,
      scheduleDayOfMonth,
      lastRunAt: editingAutomation?.lastRunAt,
      
      purpose:
        purpose.trim() ||
        `Run a repeatable ${category.toLowerCase()} workflow.`,
      prompt: prompt.trim(),
      output:
        output.trim() ||
        'A structured deliverable generated by the agent.',
      outputType: outputType.trim() || DEFAULT_OUTPUT_TYPE,
      outputDestination: finalOutputDestination,
      outputDestinationLabel,
      goodFor:
        editingAutomation?.goodFor?.length
          ? editingAutomation.goodFor
          : ['Custom workflow', 'Agent execution', 'Reusable output'],
      createdAt: editingAutomation?.createdAt ?? new Date().toISOString(),
    }));
  };

  return (
    <section className="mb-10 rounded-3xl border border-light-200 bg-light-secondary p-6 shadow-sm dark:border-dark-200 dark:bg-dark-secondary">
      <div className="mb-6 flex items-start justify-between gap-4">
        <div>
          <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-light-200 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-black/45 dark:border-dark-200 dark:text-white/45">
            {isEditing ? <PencilLine size={14} /> : <Plus size={14} />}
            {isEditing ? t('automationsPage.editAutomation') : t('automationsPage.newAutomation')}
          </div>

          <h2 className="text-2xl font-bold text-black dark:text-white">
            {isEditing
              ? t('automationsPage.editAutomationTitle')
              : t('automationsPage.createCustomAutomation')}
          </h2>

          <p className="mt-2 max-w-2xl text-sm leading-relaxed text-black/55 dark:text-white/55">
            {isEditing
              ? t('automationsPage.editDescription')
              : t('automationsPage.createDescription')}
          </p>
        </div>

        <button
          type="button"
          onClick={onCancel}
          className="rounded-full p-2 text-black/45 transition hover:bg-light-primary hover:text-black dark:text-white/45 dark:hover:bg-dark-primary dark:hover:text-white"
          aria-label={t('automationsPage.closeBuilder')}
        >
          <X size={20} />
        </button>
      </div>

      <form onSubmit={handleSubmit} className="grid gap-5">
        <div className="grid gap-5 md:grid-cols-2">
          <label className="space-y-2">
            <span className="text-sm font-medium text-black dark:text-white">
              {t('automationsPage.automationName')}
            </span>
            <input
              value={name}
              onChange={(event) => setName(event.target.value)}
              placeholder={t('automationsPage.automationNamePlaceholder')}
              className="w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
            />
          </label>

          <label className="space-y-2">
            <span className="text-sm font-medium text-black dark:text-white">
              {t('automationsPage.category')}
            </span>
            <input
              value={category}
              onChange={(event) => setCategory(event.target.value)}
              placeholder={t('automationsPage.categoryPlaceholder')}
              className="w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
            />
          </label>
        </div>

        <label className="space-y-2">
          <span className="text-sm font-medium text-black dark:text-white">
            {t('automationsPage.frequency')}
          </span>
          <input
            value={frequency}
            onChange={(event) => setFrequency(event.target.value)}
            placeholder={t('automationsPage.frequencyPlaceholder')}
            className="w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
          />
        </label>
        <div className="grid gap-5 md:grid-cols-2">
          <label className="space-y-2">
            <span className="text-sm font-medium text-black dark:text-white">
              {t('automationsPage.automationMode')}
            </span>
            <select
              value={mode}
              onChange={(event) => setMode(event.target.value as AutomationMode)}
              className="w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
            >
              <option value="manual">{t('automationsPage.manualOption')}</option>
              <option value="auto">{t('automationsPage.autoOption')}</option>
            </select>
          </label>

          <label className="space-y-2">
            <span className="text-sm font-medium text-black dark:text-white">
              {t('automationsPage.status')}
            </span>
            <select
              value={status}
              onChange={(event) => setStatus(event.target.value as AutomationStatus)}
              className="w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
            >
              <option value="active">{t('automationsPage.active')}</option>
              <option value="paused">{t('automationsPage.paused')}</option>
            </select>
          </label>
        </div>

        <div className="rounded-3xl border border-light-200 bg-light-primary p-5 dark:border-dark-200 dark:bg-dark-primary">
          <div className="mb-5">
            <h3 className="text-sm font-semibold text-black dark:text-white">
              {t('automationsPage.scheduleSettings')}
            </h3>

            <p className="mt-1 text-xs text-black/50 dark:text-white/50">
              {t('automationsPage.scheduleDescription')}
            </p>

            <button
              type="button"
              onClick={setTestScheduleInTwoMinutes}
              className="mt-4 inline-flex items-center justify-center rounded-full border border-light-200 px-4 py-2 text-xs font-semibold text-black/60 transition hover:bg-light-secondary hover:text-black dark:border-dark-200 dark:text-white/60 dark:hover:bg-dark-secondary dark:hover:text-white"
            >
              {t('automationsPage.testInTwoMinutes')}
            </button>
          </div>

          <div className="grid gap-5 md:grid-cols-2">
            <label className="space-y-2">
              <span className="text-sm font-medium text-black dark:text-white">
                {t('automationsPage.scheduleType')}
              </span>

              <select
                value={scheduleType}
                onChange={(event) =>
                  setScheduleType(event.target.value as AutomationScheduleType)
                }
                className="w-full rounded-2xl border border-light-200 bg-light-secondary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-secondary dark:text-white dark:focus:border-white"
              >
                <option value="manual">{t('automationsPage.manualOnly')}</option>
                <option value="daily">{t('automationsPage.daily')}</option>
                <option value="weekly">{t('automationsPage.weekly')}</option>
                <option value="monthly">{t('automationsPage.monthly')}</option>
              </select>
            </label>

            <label className="space-y-2">
              <span className="text-sm font-medium text-black dark:text-white">
                {t('automationsPage.time')}
              </span>

              <input
                type="time"
                value={scheduleTime}
                onChange={(event) => setScheduleTime(event.target.value)}
                className="w-full rounded-2xl border border-light-200 bg-light-secondary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-secondary dark:text-white dark:focus:border-white"
              />
            </label>
          </div>

          {scheduleType === 'weekly' && (
            <div className="mt-5">
              <p className="mb-3 text-sm font-medium text-black dark:text-white">
                {t('automationsPage.days')}
              </p>

              <div className="flex flex-wrap gap-2">
                {WEEKDAY_OPTIONS.map((day) => {
                  const selected = scheduleDays.includes(day.value);

                  return (
                    <button
                      key={day.value}
                      type="button"
                      onClick={() =>
                        setScheduleDays((current) =>
                          selected
                            ? current.filter((item) => item !== day.value)
                            : [...current, day.value],
                        )
                      }
                      className={`rounded-full border px-3 py-1.5 text-xs font-semibold transition ${
                        selected
                          ? 'border-black bg-black text-white dark:border-white dark:bg-white dark:text-black'
                          : 'border-light-200 text-black/55 hover:bg-light-secondary dark:border-dark-200 dark:text-white/55 dark:hover:bg-dark-secondary'
                      }`}
                    >
                      {t(day.labelKey)}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {scheduleType === 'monthly' && (
            <label className="mt-5 block space-y-2">
              <span className="text-sm font-medium text-black dark:text-white">
                {t('automationsPage.dayOfMonth')}
              </span>

              <input
                type="number"
                min={1}
                max={31}
                value={scheduleDayOfMonth}
                onChange={(event) =>
                  setScheduleDayOfMonth(
                    Math.min(31, Math.max(1, Number(event.target.value) || 1)),
                  )
                }
                className="w-full rounded-2xl border border-light-200 bg-light-secondary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-secondary dark:text-white dark:focus:border-white"
              />
            </label>
          )}
        </div>

        <label className="space-y-2">
          <span className="text-sm font-medium text-black dark:text-white">
            {t('automationsPage.objective')}
          </span>
          <textarea
            value={purpose}
            onChange={(event) => setPurpose(event.target.value)}
            placeholder={t('automationsPage.objectivePlaceholder')}
            rows={3}
            className="w-full resize-none rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
          />
        </label>

        <label className="space-y-2">
          <span className="text-sm font-medium text-black dark:text-white">
            {t('automationsPage.agentInstructions')}
          </span>
          <textarea
            value={prompt}
            onChange={(event) => setPrompt(event.target.value)}
            placeholder={t('automationsPage.agentInstructionsPlaceholder')}
            rows={5}
            className="w-full resize-none rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
          />
        </label>

        <label className="space-y-2">
          <span className="text-sm font-medium text-black dark:text-white">
            {t('automationsPage.expectedOutput')}
          </span>
          <textarea
            value={output}
            onChange={(event) => setOutput(event.target.value)}
            placeholder={t('automationsPage.expectedOutputPlaceholder')}
            rows={3}
            className="w-full resize-none rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
          />
        </label>

        <div className="grid gap-5 md:grid-cols-2">
          <label className="space-y-2">
            <span className="text-sm font-medium text-black dark:text-white">
              {t('automationsPage.outputType')}
            </span>
            <select
              value={outputType}
              onChange={(event) => setOutputType(event.target.value)}
              className="w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
            >
              {OUTPUT_TYPES.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </label>

          <label className="space-y-2">
            <span className="text-sm font-medium text-black dark:text-white">
              {t('automationsPage.saveDestination')}
            </span>
            <select
              value={outputDestination}
              onChange={(event) => setOutputDestination(event.target.value)}
              className="w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
            >
              <option value={DEFAULT_OUTPUT_DESTINATION}>
                {t('automationsPage.automationOutputs')}
              </option>

              <option value={NEW_SPACE_DESTINATION}>
                {t('automationsPage.createNewSpace')}
              </option>

              {spaces.map((space) => (
                <option key={space.id} value={`space:${space.id}`}>
                  {space.name} Space
                </option>
              ))}
            </select>

            {outputDestination === NEW_SPACE_DESTINATION && (
              <input
                value={newSpaceName}
                onChange={(event) => setNewSpaceName(event.target.value)}
                placeholder={t('automationsPage.newSpaceName')}
                className="mt-3 w-full rounded-2xl border border-light-200 bg-light-primary px-4 py-3 text-sm text-black outline-none transition focus:border-black dark:border-dark-200 dark:bg-dark-primary dark:text-white dark:focus:border-white"
              />
            )}
          </label>
        </div>

        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-end">
          <button
            type="button"
            onClick={onCancel}
            className="rounded-full border border-light-200 px-5 py-2.5 text-sm font-semibold text-black/65 transition hover:bg-light-primary hover:text-black dark:border-dark-200 dark:text-white/65 dark:hover:bg-dark-primary dark:hover:text-white"
          >
            {t('automationsPage.cancel')}
          </button>

          <button
            type="submit"
            disabled={!canSave}
            className="inline-flex items-center justify-center gap-2 rounded-full bg-black px-5 py-2.5 text-sm font-semibold text-white transition hover:scale-[1.01] active:scale-[0.99] disabled:cursor-not-allowed disabled:opacity-40 dark:bg-white dark:text-black"
          >
            <Save size={16} />
            {isEditing ? t('automationsPage.saveChanges') : t('automationsPage.createAutomation')}
          </button>
        </div>
      </form>
    </section>
  );
};
