use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: 'SEARXNG_SECRET_PLACEHOLDER'
  limiter: false
  public_instance: false

engines:
  - name: wolframalpha
    disabled: false